// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oemoezexfuwdxgwzolpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbW9lemV4ZnV3ZHhnd3pvbHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDI2OTYsImV4cCI6MjA2NDM3ODY5Nn0.g-zyMnzpCJ1frDj0zcmPfsmwsecUGif6fZXd1a0IJ9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);